#!/bin/sh

# openjdk-8-jre
export JAVA_HOME=$SNAP/usr/lib/jvm/java-8-openjdk-$SNAP_ARCH
export PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH
 
# fonts
export XDG_DATA_HOME=$SNAP/usr/share
export FONTCONFIG_PATH=$SNAP/etc/fonts/config.d
export FONTCONFIG_FILE=$SNAP/etc/fonts/fonts.conf
 
# archaeopteryx configuration file
config=_aptx_configuration_file
[ -e "$SNAP_USER_DATA/$config" ] || cp $SNAP/$config $SNAP_USER_DATA

java -Duser.home=$SNAP_USER_DATA -jar $SNAP/bin/forester.jar -c $SNAP/_aptx_configuration_file "$@"
